### ISSUE TITLE
Submission edit page doesn't fill checkboxes

### ISSUE THREAD

**Issue by aviator8808** [isoboroff/submit-system#14]
![image](https://github.com/isoboroff/submit-system/assets/133380352/d5785419-f973-44f5-a59f-a53f3f5cad9f)

**Comment by aviator8808** [comment]
Check for bootstrap updates
(File is removed on form error)

**Comment by isoboroff** [comment]
Fixed by PR #28, e5a787f8f11430fb4b17c480a62a7e67a1db022f
